#!/bin/bash

PKG_NAME="phpvirtualbox"
INST_DIR="/tmp/_${PKG_NAME}"
PKG_DIR="/tmp/_${PKG_NAME}_pkg"
PKG_DEST="/image/packages"
DATE=$(date +%Y%m%d) 
SRC=$(pwd)

PrepareDirs() {
    for dir in $INST_DIR $PKG_DIR; do
        rm -rf "$dir"
    done
    for dir in $INST_DIR $PKG_DIR $PKG_DEST; do
        mkdir -p "$dir"
    done
}

Install() {
	### what platform is this
	case "$BUILD_TARGET" in
		PPC_QORIQ)
				echo "PPC_QORIQ is unsupported platform!"
				exit 1
				;;
			X64)
				PLATFORM="x86_64"
				;;
			BROMOLOWESM|BROMOLOW)
				PLATFORM="bromolow"
				;;
			MARVELL_88F6281)
				echo "MARVELL_88F6281 is unsupported platform!"
				exit 1
				;;
			*)
				echo "${BUILD_TARGET} unsupported platform!"
				exit 1
				;;
	esac
	 
	cp -r package/* "${INST_DIR}/"

	# fix permissions
	chown root:root ${INST_DIR} -R
}

GenerateINFO() {
	### Generate INFO file
	./INFO.sh "${DSM_SHLIB_MAJOR}.${DSM_SHLIB_MINOR}-${DSM_BUILD_NUM}" "${DATE}" > spk/INFO
    #./INFO.sh > spk/INFO
    cp spk/INFO "${PKG_DIR}"
    cp spk/INFO INFO
}

InstallSynologyConfig(){
	### Copy licence
	cp -av spk/LICENSE "${PKG_DIR}"
    cp -r spk/scripts/ "${PKG_DIR}"
    cp spk/PACKAGE_ICON{,_256}.PNG "${PKG_DIR}"
	cp -r spk/WIZARD_UIFILES/ "${PKG_DIR}"
}

MakePackage() {
	[ -f /pkgscripts/include/pkg_util.sh ] && source /pkgscripts/include/pkg_util.sh
	[ -f /pkgscripts-ng/include/pkg_util.sh ] && source /pkgscripts-ng/include/pkg_util.sh
    

    ### fix permissions
    chown root:root $PKG_DIR/* -R

    pkg_make_package $INST_DIR $PKG_DIR
    pkg_make_spk $PKG_DIR $PKG_DEST 
}

main() {
    PrepareDirs
    Install
    GenerateINFO
    InstallSynologyConfig
    MakePackage 
}

main "$@"
